# Generated by Django 4.1.13 on 2024-07-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription_subscription',
        ),
    ]
