# Generated by Django 4.1.13 on 2024-07-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(max_length=20, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('num_people', models.IntegerField(default=1)),
                ('reference_name', models.CharField(max_length=100)),
            ],
        ),
    ]
