# Generated by Django 4.1.13 on 2024-07-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_dailypass_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPass',
        ),
    ]
