# Generated by Django 4.1.13 on 2024-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FileField(upload_to='vehicles/'),
        ),
    ]
