# Generated by Django 4.1.13 on 2024-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceweb', '0002_alter_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
