# Generated by Django 4.1.13 on 2024-07-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceweb', '0003_allowedperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDBSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snapshots')),
                ('timestamp', models.DateTimeField()),
                ('format', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MongoDB Snapshot',
                'verbose_name_plural': 'MongoDB Snapshots',
                'managed': False,
            },
        ),
    ]
